baseURL: https://www.amansharma.co.uk/
languageCode: en-us
title: Aman Sharma
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Learn More
    subtitle: |-
      Welcome to my personal website!
    title: Aman Sharma
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: amanakshay@gmail.com
        title: Email
    enable: yes
    phone:
      - phone: (+44) 791-5878 952
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com
  image: ''
  name: Aman Sharma
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: elements.html
    menu: Menu
    subtitle: Sharma
    title: Aman
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Post 1
        url: blogs/test4
      - image: pic02.jpg
        subtitle: Feugiat Amet Tempus
        title: Post 2
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Post 3
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Post 4
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Post 5
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Post 6
        url: blogs/ipsum
  two:
    buttonText: Learn More
    enable: yes
    subtitle: "Hello, thanks for checking out my website. My name is Aman, a 22 year old from Berkshire, a county in the South East of England."
    title: About Me
    url: blogs
