[build]
publish = "public"
command = "hugo"

[build.environment]
HUGO_VERSION = "0.81.0"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_VERSION = "0.81.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.81.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.81.0"
